# Generated by Django 3.2.4 on 2021-07-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmodel',
            old_name='Text',
            new_name='text',
        ),
    ]
